# Generated by Django 4.1.6 on 2023-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200, null=True)),
                ('game_active', models.BooleanField(default=False)),
            ],
        ),
    ]
